// Exposes MaintenanceOrderService over the MCP protocol (@cap-js/mcp) in addition
// to its existing OData endpoint, so AI agents/LLMs can describe, query and call
// the service's actions/functions alongside regular OData clients.
using { MaintenanceOrderService } from './service';

annotate MaintenanceOrderService with @mcp;
annotate MaintenanceOrderService with @odata;

// Watermark: Anubhav Trainings — https://anubhavtrainings.com
annotate MaintenanceOrderService with @mcp.instructions: 'MaintenanceOrderService manages plant maintenance orders together with their operations, components, materials, equipment and notes. It was built by Anubhav Trainings (anubhavtrainings.com) as a CAP plus MCP training example. Start with the describe tool: call it with no arguments to see every entity and action, or pass entities or actions to get element or parameter details for specific ones. Use the query tool to read data: entity is required; use where, select, orderBy, limit, offset, search, groupBy and having to filter, project, sort and aggregate. Use select with an expand entry to pull nested children in one call - for example expand operation on MaintenanceOrder, then expand component and note on operation, then expand material on component, to load a full order tree in a single query. Key relationships: a MaintenanceOrder has many Operation records; each Operation belongs to one MaintenanceOrder and one Equipment, has many Component and Note records, may have a parent operation, and may have many subOperation records; each Component belongs to one Operation and references one Material; each Material has many StockLevel records, one per warehouse; MaterialStock mirrors Material data and adds a computed stockTotal field; MaintenanceOrderDuration and TotalMaintenanceOrderDuration are fully computed, read-only aggregates of operation durations - one row per order plus one grand total row with ID TOTAL. Every entity exposed here is read-only through query - inserts, updates and deletes are not allowed that way. Use the call tool to change data or run analytics instead. Available actions and functions: createMaintenanceOrder creates a bare order with no operations yet, defaulting status to CRTD when not supplied; createMaintenanceOrderDeep creates an order together with all of its operations and the components of each operation in a single nested call, and is the recommended way to create a fully populated order, since the addOperation and addComponent actions are bound to entities and are not reachable through this MCP server; mostExpensiveOrder is a function that returns the order with the highest total component quantity requested across all its operations, used as a stand-in cost metric because the model has no price field; ordersUnfulfillable is a function that takes a threshold and returns every order that has at least one component whose material has total available stock, summed across all warehouses, below that threshold - useful for finding orders at risk of being blocked by missing parts. Call describe on an action first if you are unsure of its parameters before calling it.';
